export interface KeralaDistrictLocation {
  id: string;
  nameEn: string;
  nameMl: string;
  districtEn: string;
  districtMl: string;
  state: string;
  country: string;
  lat: number;
  lng: number;
  timezone: string; // "Asia/Kolkata"
  tzOffset: number; // +5.5
}

export const KERALA_LOCATIONS: KeralaDistrictLocation[] = [
  {
    id: "thiruvananthapuram",
    nameEn: "Thiruvananthapuram",
    nameMl: "തിരുവനന്തപുരം",
    districtEn: "Thiruvananthapuram",
    districtMl: "തിരുവനന്തപുരം",
    state: "Kerala",
    country: "India",
    lat: 8.5241,
    lng: 76.9366,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "kollam",
    nameEn: "Kollam",
    nameMl: "കൊല്ലം",
    districtEn: "Kollam",
    districtMl: "കൊല്ലം",
    state: "Kerala",
    country: "India",
    lat: 8.8932,
    lng: 76.6141,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "pathanamthitta",
    nameEn: "Pathanamthitta",
    nameMl: "പത്തനംതിട്ട",
    districtEn: "Pathanamthitta",
    districtMl: "പത്തനംതിട്ട",
    state: "Kerala",
    country: "India",
    lat: 9.2648,
    lng: 76.7870,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "alappuzha",
    nameEn: "Alappuzha",
    nameMl: "ആലപ്പുഴ",
    districtEn: "Alappuzha",
    districtMl: "ആലപ്പുഴ",
    state: "Kerala",
    country: "India",
    lat: 9.4981,
    lng: 76.3388,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "kottayam",
    nameEn: "Kottayam",
    nameMl: "കോട്ടയം",
    districtEn: "Kottayam",
    districtMl: "കോട്ടയം",
    state: "Kerala",
    country: "India",
    lat: 9.5916,
    lng: 76.5222,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "idukki",
    nameEn: "Idukki (Painavu)",
    nameMl: "ഇടുക്കി (പൈനാവ്)",
    districtEn: "Idukki",
    districtMl: "ഇടുക്കി",
    state: "Kerala",
    country: "India",
    lat: 9.8500,
    lng: 76.9700,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "ernakulam",
    nameEn: "Ernakulam (Kochi)",
    nameMl: "എറണാകുളം (കൊച്ചി)",
    districtEn: "Ernakulam",
    districtMl: "എറണാകുളം",
    state: "Kerala",
    country: "India",
    lat: 9.9312,
    lng: 76.2673,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "thrissur",
    nameEn: "Thrissur",
    nameMl: "തൃശ്ശൂർ",
    districtEn: "Thrissur",
    districtMl: "തൃശ്ശൂർ",
    state: "Kerala",
    country: "India",
    lat: 10.5276,
    lng: 76.2144,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "palakkad",
    nameEn: "Palakkad",
    nameMl: "പാലക്കാട്",
    districtEn: "Palakkad",
    districtMl: "പാലക്കാട്",
    state: "Kerala",
    country: "India",
    lat: 10.7867,
    lng: 76.6548,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "malappuram",
    nameEn: "Malappuram",
    nameMl: "മലപ്പുറം",
    districtEn: "Malappuram",
    districtMl: "മലപ്പുറം",
    state: "Kerala",
    country: "India",
    lat: 11.0510,
    lng: 76.0711,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "kozhikode",
    nameEn: "Kozhikode (Calicut)",
    nameMl: "കോഴിക്കോട്",
    districtEn: "Kozhikode",
    districtMl: "കോഴിക്കോട്",
    state: "Kerala",
    country: "India",
    lat: 11.2588,
    lng: 75.7804,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "wayanad",
    nameEn: "Wayanad (Kalpetta)",
    nameMl: "വയനാട് (കൽപ്പറ്റ)",
    districtEn: "Wayanad",
    districtMl: "വയനാട്",
    state: "Kerala",
    country: "India",
    lat: 11.6854,
    lng: 76.1320,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "kannur",
    nameEn: "Kannur",
    nameMl: "കണ്ണൂർ",
    districtEn: "Kannur",
    districtMl: "കണ്ണൂർ",
    state: "Kerala",
    country: "India",
    lat: 11.8745,
    lng: 75.3704,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
  {
    id: "kasaragod",
    nameEn: "Kasaragod",
    nameMl: "കാസർഗോഡ്",
    districtEn: "Kasaragod",
    districtMl: "കാസർഗോഡ്",
    state: "Kerala",
    country: "India",
    lat: 12.4996,
    lng: 74.9869,
    timezone: "Asia/Kolkata",
    tzOffset: 5.5,
  },
];

export const DEFAULT_KERALA_LOCATION = KERALA_LOCATIONS[0]; // Thiruvananthapuram
